# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_db_instance.mydatabase:
resource "aws_db_instance" "mydatabase" {
  allocated_storage          = 64
  auto_minor_version_upgrade = false
  backup_retention_period    = 3
  backup_window              = "22:43-23:13"
  ca_cert_identifier         = "rds-ca-2019"
  character_set_name         = "AL32UTF8"
  copy_tags_to_snapshot      = true
  #db_subnet_group_name = "default"
  delete_automated_backups = true
  deletion_protection      = false
  enabled_cloudwatch_logs_exports = [
    "alert",
    "audit",
  ]
  engine                              = "oracle-ee"
  engine_version                      = "18.0.0.0.ru-2020-10.rur-2020-10.r1"
  iam_database_authentication_enabled = false
  identifier                          = "mydatabase"
  instance_class                      = "db.m5.xlarge"
  iops                                = 0
  #kms_key_id = "arn:aws:kms:eu-west-1:463726854253:key/04bcd32d-afd0-499b-9487-e0e34a203e39"
  license_model         = "bring-your-own-license"
  maintenance_window    = "sun:01:26-sun:01:56"
  max_allocated_storage = 1000
  monitoring_interval   = 60
  monitoring_role_arn   = format("arn:aws:iam::%s:role/rds-monitoring-role", data.aws_caller_identity.current.account_id)
  #monitoring_role_arn = "arn:aws:iam::463726854253:role/rds-monitoring-role"
  multi_az                     = true
  name                         = "ORCL"
  option_group_name            = "default:oracle-ee-18"
  parameter_group_name         = "default.oracle-ee-18"
  performance_insights_enabled = true
  #performance_insights_kms_key_id = "arn:aws:kms:eu-west-1:463726854253:key/04bcd32d-afd0-499b-9487-e0e34a203e39"
  performance_insights_retention_period = 2
  port                                  = 1521
  publicly_accessible                   = true

  security_group_names = []
  skip_final_snapshot  = true
  storage_encrypted    = true
  storage_type         = "gp3"
  tags                 = {}
  username             = "oraadmin"
  vpc_security_group_ids = [
    data.aws_security_group.sg-ora.id,
  ]

  timeouts {}
}
