# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.TeamRole:
resource "aws_iam_role" "rds-monitoring-role" {
  assume_role_policy = jsonencode(
    {
      "Version" : "2012-10-17",
      "Statement" : [
        {
          "Sid" : "",
          "Effect" : "Allow",
          "Principal" : {
            "Service" : "monitoring.rds.amazonaws.com"
          },
          "Action" : "sts:AssumeRole"
        }
      ]
    }
  )
  force_detach_policies = false
  max_session_duration  = 43200
  name                  = "rds-monitoring-role"
  path                  = "/"
  tags                  = {}
}
