-- Drops all tables in TPCE schema

DROP TABLE account_permission CASCADE CONSTRAINTS PURGE;

DROP TABLE customer CASCADE CONSTRAINTS PURGE;

DROP TABLE customer_account CASCADE CONSTRAINTS PURGE;

DROP TABLE customer_taxrate CASCADE CONSTRAINTS PURGE;

DROP TABLE holding CASCADE CONSTRAINTS PURGE;

DROP TABLE holding_history CASCADE CONSTRAINTS PURGE;

DROP TABLE holding_summary CASCADE CONSTRAINTS PURGE;

DROP TABLE watch_item CASCADE CONSTRAINTS PURGE;

DROP TABLE watch_list CASCADE CONSTRAINTS PURGE;

DROP TABLE broker CASCADE CONSTRAINTS PURGE;

DROP TABLE cash_transaction CASCADE CONSTRAINTS PURGE;

DROP TABLE charge CASCADE CONSTRAINTS PURGE;

DROP TABLE commission_rate CASCADE CONSTRAINTS PURGE;

DROP TABLE settlement CASCADE CONSTRAINTS PURGE;

DROP TABLE trade CASCADE CONSTRAINTS PURGE;

DROP TABLE trade_history CASCADE CONSTRAINTS PURGE;

DROP TABLE trade_request CASCADE CONSTRAINTS PURGE;

DROP TABLE trade_type CASCADE CONSTRAINTS PURGE;

DROP TABLE company CASCADE CONSTRAINTS PURGE;

DROP TABLE company_competitor CASCADE CONSTRAINTS PURGE;

DROP TABLE daily_market CASCADE CONSTRAINTS PURGE;

DROP TABLE exchange CASCADE CONSTRAINTS PURGE;

DROP TABLE financial CASCADE CONSTRAINTS PURGE;

DROP TABLE industry CASCADE CONSTRAINTS PURGE;

DROP TABLE last_trade CASCADE CONSTRAINTS PURGE;

DROP TABLE news_item CASCADE CONSTRAINTS PURGE;

DROP TABLE news_xref CASCADE CONSTRAINTS PURGE;

DROP TABLE sector CASCADE CONSTRAINTS PURGE;

DROP TABLE address CASCADE CONSTRAINTS PURGE;

DROP TABLE security CASCADE CONSTRAINTS PURGE;

DROP TABLE status_type CASCADE CONSTRAINTS PURGE;

DROP TABLE tax_rate CASCADE CONSTRAINTS PURGE;

DROP TABLE zip_code CASCADE CONSTRAINTS PURGE;

-- End
